// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fill_cell_gene
List fill_cell_gene(const char* fn, List genes, std::vector<std::string> whitelist, int est_ncells, int est_ngenes, bool display_progress);
RcppExport SEXP _BUStoolsR_fill_cell_gene(SEXP fnSEXP, SEXP genesSEXP, SEXP whitelistSEXP, SEXP est_ncellsSEXP, SEXP est_ngenesSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< List >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type whitelist(whitelistSEXP);
    Rcpp::traits::input_parameter< int >::type est_ncells(est_ncellsSEXP);
    Rcpp::traits::input_parameter< int >::type est_ngenes(est_ngenesSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_cell_gene(fn, genes, whitelist, est_ncells, est_ngenes, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BUStoolsR_fill_cell_gene", (DL_FUNC) &_BUStoolsR_fill_cell_gene, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_BUStoolsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
