# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EC2gene_export <- function(tr2g, kallisto_out_path, verbose = TRUE) {
    .Call('_BUSpaRse_EC2gene_export', PACKAGE = 'BUSpaRse', tr2g, kallisto_out_path, verbose)
}

fill_cell_gene <- function(fn, kallisto_out_path, tr2g, est_ncells, est_ngenes, whitelist, gene_count = TRUE, tcc = TRUE, single_gene = TRUE, verbose = TRUE, progress_unit = 5e6L) {
    .Call('_BUSpaRse_fill_cell_gene', PACKAGE = 'BUSpaRse', fn, kallisto_out_path, tr2g, est_ncells, est_ngenes, whitelist, gene_count, tcc, single_gene, verbose, progress_unit)
}

