# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert the output of kallisto into gene by cell matrix
#' 
#' This function takes the output file, usually \code{output.sort.txt}, from kallisto,
#' which has 4 columns: barcode, UMI, equivalence class, and counts, and generates
#' the row indices, column pointers, gene UMI count values, accepted barcodes, 
#' and genes (for dim names) to be used in R to construct a sparse matrix.
#' 
#' @param fn File name of the kallisto main output file.
#' @param genes A list with each element a string vector of genes that an equivalence
#' class maps to, generated earlier in R.
#' @param whitelist A string vector showing whiteliisted barcodes from 10x.
#' @param est_ncells Estimated number of cells; providing this argument will
#' speed up computation as it minimizes memory reallocation as vectors grow.
#' @param est_ngenes Estimated number of genes.
#' @param display_progress Whether to display progress.
#' 
#' @return A list with row indices, column pointers, gene UMI count values, 
#' barcodes (for column names), and gene IDs (for row names). You should construct
#' the sparse matrix in R.
#' @export
fill_cell_gene <- function(fn, genes, whitelist, est_ncells, est_ngenes, display_progress = TRUE) {
    .Call(`_BUStoolsR_fill_cell_gene`, fn, genes, whitelist, est_ncells, est_ngenes, display_progress)
}

